version: '3'
services: 
  database: 
    image: 'postgres:10'
    container_name: 'booklub-database'
    networks: 
      - booklub-network
    ports: 
      - 5432:5432
    volumes: 
      - ./db/data:/var/lib/postgresql/data
      - ./db/migration:/var/lib/postgresql/migration
    environment: 
      - POSTGRES_USER=jlano
      - POSTGRES_PASSWORD=monkey
      - POSTGRES_DB=booklub
  admin:
    image: 'thajeztah/pgadmin4'
    container_name: 'booklub-database-admin'
    networks:
      - booklub-network
    ports:
      - 5050:5050
networks: 
  booklub-network: 
    driver: bridge
